### ISSUE TITLE
Question : Is there a different naming convention for Core Data entities?

### ISSUE THREAD

**Issue by olympianoiseco** [NYTimes/objective-c-style-guide#121]
In most Core Data examples, I see people naming entities without a prefix.  i.e. Person instead of ONCPerson.  Which, of course, means that you end up with subclasses of NSManagedObject that have no prefix.  

Is that standard practice?

**Comment by cdzombak** [comment]
It's fairly common for your _entity_ names not to have prefixes; names like `Article` or `Person` are typical, in my experience.

> Which, of course, means that you end up with subclasses of NSManagedObject that have no prefix.

This isn't necessarily true. In the Core Data model editor, you can assign class names _with_ prefixes to your entities:

![screen shot 2015-04-27 at 12 54 36](https://cloud.githubusercontent.com/assets/102904/7352811/af12cb2c-ecdc-11e4-9f11-94679fcf2011.png)

This has been the case in most Core Data projects I've worked on, but I don't know how standard it is across the industry.

_Will leave this issue open for discussion for a few more days, unless @olympianoiseco wishes to close it._

**Comment by paulbruneau** [comment]
In my project, The entities have no prefix, but the class does, just as above.

**Comment by olympianoiseco** [comment]
Thanks!
