### ISSUE TITLE
More In-depth Explanations Where Possible

### ISSUE THREAD

**Issue by bcapps** [NYTimes/objective-c-style-guide#15]
There are a few sections where we discussed motivations behind style choices in-person on our team and simply didn't explain, but there are also some that we cut when releasing publicly because they were too conversational in tone or not well-enough explained. The `CGGemoetry` functions section has a relevant quite that provides ample explanation for our reasoning, which that would serve us well in some other sections.

Dot notation, spacing, and some other sections are light on the reasoning even though we have considered each choice carefully. Some other sections are small stylistic choices that are pretty binary, but those need little explanation except preference.

**Comment by Twigz** [comment]
If there are specific things we should go in depth on further, lets call them out specifically. Otherwise closing for now.

**Comment by cdzombak** [comment]
> If there are specific things we should go in depth on further, lets call them out specifically.

We welcome new issues with suggestions or questions about items which are unclear or could use further clarification.
