### ISSUE TITLE
Apple objetive C documet link don't work

### ISSUE THREAD

**Issue by orestesleal** [nytimes/objective-c-style-guide#162]
http://developer.apple.com/library/mac/#documentation/Cocoa/Conceptual/ObjectiveC/Introduction/introObjectiveC.html

**Comment by TheMacNerd** [comment]
You have to type "ConfigureIncomingContent()" (minus the quotes).  The source for my answer is below.


https://stackoverflow.com/questions/38321880/how-to-go-about-adding-a-link-reference-to-another-method-in-documentation-xcode

**Comment by stelladrop** [comment]
You have to type "ConfigureIncomingContent()" (minus the quotes). The source for my answer is below.

**Comment by patsybond172** [comment]
[https://github.com/patsybond172](https://github.com/patsybond172)
