### ISSUE TITLE
printing prime numbers in N range without using function in python

### ISSUE THREAD

**Issue by nshutijonathan** [nytimes/objective-c-style-guide#172]
hello everyone i want to print numbers between 1 and  200 without using user-defined function in my program, i want codes of python

**Comment by peterhuerlimann** [comment]
Hi @nshutijonathan 

Places like https://stackoverflow.com/questions/tagged/python/, https://www.reddit.com/r/learnpython/ or https://python-forum.io/ would probably be better suited for your question.

Kind regards
Peter

**Comment by alexwal** [comment]
Try this:

print(1)
print(2)
print(3)
print(4)
print(5)
print(6)
print(7)
print(8)
print(9)
print(10)
print(11)
print(12)
print(13)
print(14)
print(15)
print(16)
print(17)
print(18)
print(19)
print(20)
print(21)
print(22)
print(23)
print(24)
print(25)
print(26)
print(27)
print(28)
print(29)
print(30)
print(31)
print(32)
print(33)
print(34)
print(35)
print(36)
print(37)
print(38)
print(39)
print(40)
print(41)
print(42)
print(43)
print(44)
print(45)
print(46)
print(47)
print(48)
print(49)
print(50)
print(51)
print(52)
print(53)
print(54)
print(55)
print(56)
print(57)
print(58)
print(59)
print(60)
print(61)
print(62)
print(63)
print(64)
print(65)
print(66)
print(67)
print(68)
print(69)
print(70)
print(71)
print(72)
print(73)
print(74)
print(75)
print(76)
print(77)
print(78)
print(79)
print(80)
print(81)
print(82)
print(83)
print(84)
print(85)
print(86)
print(87)
print(88)
print(89)
print(90)
print(91)
print(92)
print(93)
print(94)
print(95)
print(96)
print(97)
print(98)
print(99)
print(100)
print(101)
print(102)
print(103)
print(104)
print(105)
print(106)
print(107)
print(108)
print(109)
print(110)
print(111)
print(112)
print(113)
print(114)
print(115)
print(116)
print(117)
print(118)
print(119)
print(120)
print(121)
print(122)
print(123)
print(124)
print(125)
print(126)
print(127)
print(128)
print(129)
print(130)
print(131)
print(132)
print(133)
print(134)
print(135)
print(136)
print(137)
print(138)
print(139)
print(140)
print(141)
print(142)
print(143)
print(144)
print(145)
print(146)
print(147)
print(148)
print(149)
print(150)
print(151)
print(152)
print(153)
print(154)
print(155)
print(156)
print(157)
print(158)
print(159)
print(160)
print(161)
print(162)
print(163)
print(164)
print(165)
print(166)
print(167)
print(168)
print(169)
print(170)
print(171)
print(172)
print(173)
print(174)
print(175)
print(176)
print(177)
print(178)
print(179)
print(180)
print(181)
print(182)
print(183)
print(184)
print(185)
print(186)
print(187)
print(188)
print(189)
print(190)
print(191)
print(192)
print(193)
print(194)
print(195)
print(196)
print(197)
print(198)
print(199)
print(200)

**Comment by mr-fixit** [comment]
kudos, @alexwal
