### ISSUE TITLE
Archive this repository

### ISSUE THREAD

**Issue by mattbischoff** [nytimes/objective-c-style-guide#189]
If this repository and guide is no longer being maintained by @nytimes, it would be appropriate to [archive it](https://docs.github.com/en/repositories/archiving-a-github-repository/archiving-repositories), close open pull requests, stop accepting new pull requests, and make a note to that effect in the README. 

Another option would be to hand the repository over to one of the contributors that is still making use of it.

**Comment by mattbischoff** [comment]
@jlawrienyt maybe you could get this into the right hands?

**Comment by mattbischoff** [comment]
@hamman could you take care of this?

**Comment by hamman** [comment]
@ashott is on this and going to find someone to be a steward.

**Comment by mattbischoff** [comment]
Thank you!
