### ISSUE TITLE
Add an exception to naming convention for names beginning with commonly used abbrevations

### ISSUE THREAD

**Issue by mpkeefe** [nytimes/objective-c-style-guide#21]
The Naming section advises 

> Properties should be camel-case with the leading word being lowercase.

When it makes sense for a symbol name to begin with a commonly used abbreviation, then the abbreviation should be capitalized according to common convention.  In other words, the common naming convention takes precedence.   

Examples appear scattered through Apple's class references:
- `NSData *HTTPBody`
- `NSURL *URL`
- `const char *UTF8String`
- `[UIColor RedColor].CGColor`

**Comment by mattbischoff** [comment]
@mpkeefe I think a PR for this would still be great idea.
