### ISSUE TITLE
Name symbols to end in the class or primitive type they represent

### ISSUE THREAD

**Issue by mpkeefe** [NYTimes/objective-c-style-guide#28]
With Rob Rix' statement in mind that the style guide should pay special attention to less experienced programmers, a naming convention that most of us follow but isn't documented is to end symbol names in the class or primitive type they represent.  

This is especially important when dealing with a variable that is not precisely the semantic type it sounds like:

* `NSString *URLstring = [self.item.URL.absoluteString stringByReplacingPercentEscapesUsingEncoding:NSUTF8StringEncoding];`
* `NSURL *URL = [NSURL URLWithString:URLstring]`;
* `NSString *apiReleaseDateString = [currentAPIDict valueForKey:@"date"];`
* `NSDate *apiReleaseDate = [DateFormatter dateFromString:apiReleaseDateString];`

**Comment by mattbischoff** [comment]
Totally agree with @cdzombak here. Not sure how we can write it up in the guide, but it makes complete sense.

**Comment by cdzombak** [comment]
> Totally agree with @cdzombak here. Not sure how we can write it up in the guide, but it makes complete sense.

Written in #108.
