### ISSUE TITLE
The compiler's good with array.count and array.firstObject, etc. I am too. Can we be?

### ISSUE THREAD

**Issue by paulbruneau** [NYTimes/objective-c-style-guide#45]
![screen shot 2013-08-26 at 12 23 10 pm](https://f.cloud.github.com/assets/978400/1027160/dc89117a-0e6b-11e3-8759-20f2e1fd5436.png)

If they aren't a good idea, the compiler will tell us. 

Signed, 
Former anti-dot.property zealot

**Comment by cdzombak** [comment]
> I was right! Yay!

:D
