### ISSUE TITLE
Automated style checker

### ISSUE THREAD

**Issue by nick7ikin** [NYTimes/objective-c-style-guide#57]
Do you have any automated style checker on your CI-server? I've searched for tools like that and the only thing I've found is https://github.com/Cue/ocstyle, but it has hard-coded rules in python language. And seems not to be developing any more. More tools could be found [here](http://stackoverflow.com/a/21458835/3086074), but the most of them are designed to apply convention to code,  not to check the style.

**Comment by mattbischoff** [comment]
I’d recommend closing this issue in favor of #63.

**Comment by Twigz** [comment]
Closing in favor of #63
