### ISSUE TITLE
Using "!" is not more clear than "== NO"

### ISSUE THREAD

**Issue by jerryhjones** [NYTimes/objective-c-style-guide#7]
While I'm not a zealot about convincing others to move away from using `!` in conditionals, I wouldn't ever give up my use of `== NO`. Not only are inverted conditions typically harder to mentally process, using `!` in fact often _reduces_ visual clarity. Typically, this is the result of a lack of whitespace with something like `if (![object boolValue]) {` a critically important part of the condition is jumbled up with the delineation elements of the syntax. This gets worse as the complexity of your if condition increases (admittedly this is often a clarity problem in it's own rite). `if (!([obj bool1] && ![obj bool2]) {` -- quick, what is the expected result?

Truthfully, the primary reason I stopped using `!` (after vehemently arguing with a co-worker that he was silly for suggesting I avoid it) is because I caused myself a world of hurt once. During what seemed like a straight forward refactor, I managed to accidentally remove a `!`, we didn't even catch it during code review -- it was just so easy to miss. This happened to be one of those insidious bugs that ultimately took _hours_ to track down, and a fraction of a second to correct.

Don't like `== NO`? Fine, don't use it -- but don't punish the defensive coders that would like to, especially not with an empty statement like "increases visual clarity".

**Comment by mattbischoff** [comment]
This is being discussed in https://github.com/NYTimes/objective-c-style-guide/pull/100

**Comment by cdzombak** [comment]
Closing as PR #100 has been merged; see https://github.com/NYTimes/objective-c-style-guide/pull/100#issuecomment-95332815
