### ISSUE TITLE
Convention for using NSLog()

### ISSUE THREAD

**Issue by dkhamsing** [NYTimes/objective-c-style-guide#74]
Is there a convention for using `NSLog()`, I find it useful to prefix logging with the class name (can even go further and add a prefix with the method).

**Comment by mattbischoff** [comment]
Not really sure anything here is generic enough to warrant the guide, but I do think if you’re doing something like this, it might be worth investigating a logging framework or writing your own macro that wraps `NSLog()` that makes it easier.

**Comment by dkhamsing** [comment]
Yes this is exactly what I have done 

``` objc
#define DLog(fmt, ...) NSLog((@"%s [Line %d] " fmt), __PRETTY_FUNCTION__, __LINE__, ##__VA_ARGS__)        
```

**Comment by Twigz** [comment]
This seems too generic to warrant a section in the style guide. Closing for now. If you have ideas around what you think this would look like in the style guide, feel free to open a PR for discussion.
